# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exp_rs <- function(a, b) {
    .Call(`_BayMor_exp_rs`, a, b)
}

nors <- function(a, b) {
    .Call(`_BayMor_nors`, a, b)
}

urs <- function(a, b) {
    .Call(`_BayMor_urs`, a, b)
}

hnors <- function(a, b) {
    .Call(`_BayMor_hnors`, a, b)
}

rtruncnorm <- function(mu, sigma, lower, upper) {
    .Call(`_BayMor_rtruncnorm`, mu, sigma, lower, upper)
}

mor <- function(Y, l, X, nx, Nit) {
    .Call(`_BayMor_mor`, Y, l, X, nx, Nit)
}

rcpparma_hello_world <- function() {
    .Call(`_BayMor_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_BayMor_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_BayMor_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_BayMor_rcpparma_bothproducts`, x)
}

